version: "3"
services:
  cicdtestingwebsite:
    image: ycmacr.azurecr.io/cicdtesting
    ports:
      - 80:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Testing
      - HelloMessage=HELLO Testing Environment
